### PR TITLE
Chocolatey package files

### PR DESCRIPTION
**Pull request by CAMOBAP795**

### CODE REVIEW

**Comment by CAMOBAP795** [comment]
@ronaldtse I have submitted request to add CI to this repo, also I think we need to discuss several things:
 - In my opinion we should not prepare any bin packages, our installation logic will be completely in `chocolteyinstall.ps1`
 - Do we have apikey for `chocolatey` already?
 - Could you please double check all legal information from `metanorma.nuspec`
 - `README.adoc` outdated yet I will update it once we will clarify questions above

**Comment by CAMOBAP795** [comment]
1. README.adoc - updated
2. Manual deployment step added to appveyor.yml (need to be tested)
3. @ronaldtse could you please create `CHOCO_API_KEY` as described here https://www.appveyor.com/docs/build-configuration/#secure-variables and let me know encrypted value so I will update this PR

**Comment by ronaldtse** [comment]
The CHOCO_API_KEY is encrypted as this:

```yams
environment:
  my_variable:
    secure: hsyCpvNm18kiTWHdcPSN7PLra8FGfypgnSuviKQMBdY1LGnpjE4//JD1uQ+vnzU5
```

**Comment by ronaldtse** [comment]
I'm going to merge this first and let's make a second PR for the auto deploy package. Thanks @CAMOBAP795 !

**Pull request merged**
