### PR TITLE
Fix chocolatey reviewer's feedback

### PR DESCRIPTION
**Pull request by CAMOBAP795**
- https://github.com/riboseinc/chocolatey-metanorma/issues/14

### CODE REVIEW

**Comment by CAMOBAP795** [comment]
@ronaldtse PR is ready, the only issue which I need assistance is:
 - Can you point the <bugtrackerUrl> to the GitHub issues page instead of the project root?

Because as I said https://github.com/riboseinc/chocolatey-metanorma/issues/14#issuecomment-457709572 we already have `/issues` url

I think we need contact with reviewer and ask to double-check

**Comment by CAMOBAP795** [comment]
@ronaldtse I propose to merge this one and 're-tag' to submit new package for validation, how do you think?

**Comment by ronaldtse** [comment]
@CAMOBAP795 agree!

**Comment by ronaldtse** [comment]
@CAMOBAP795 I have just pinged the package reviewer about #14 .

**Pull request merged**
