### PR TITLE
Restrict max ruby version to < 2.6.0

### PR DESCRIPTION
**Pull request by CAMOBAP795**
- #11

### CODE REVIEW

**Comment by ronaldtse** [comment]
Looks good -- thank you!

**Comment by ronaldtse** [comment]
@CAMOBAP795 is the next step to build and submit the chocolatey package?

**Comment by CAMOBAP795** [comment]
@ronaldtse yep but because we automated it previously I just need to push tag, I will do it right now

**Comment by ronaldtse** [comment]
Excellent 👍

**Pull request merged**
